version: '3.7'


services:
  cms-mkt:
    build:
      context: cms-mkt
      dockerfile: ./Dockerfile
    container_name: marketplace-cms
    hostname: cms-mkt
    ports:
      - 9090:8080
    volumes:
      - type: bind
        source: ./cms-mkt/src/config/config.yaml
        target: /var/www/html/config/config.yaml
      - type: bind
        source: ./cms-mkt/src/storage
        target: /var/www/html/storage
    restart: always


  mongodbmkt:
      image: mongo:4.2.0
      container_name: marketplace-mongodbmkt
      hostname: mongodbmkt
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: cms-mongo
      volumes:
      - mongodbmkt:/data/db

  mongoke-express:
    image: mongo-express
    container_name: marketplace-mongomkt-express
    hostname: mongoke-express
    depends_on:
      - mongodbmkt
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: cms-mongo
      ME_CONFIG_MONGODB_SERVER: mongodbmkt

volumes:
  mongodbmkt: