export default {
  SET_AUTH: "SET_AUTH",
  GET_PROFILE: "GET_PROFILE",
  GET_ADDRESS: "GET_ADDRESS",
  GET_ORDERS: "GET_ORDERS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
  SET_CURRENT_SUB: "SET_CURRENT_SUB",
  CART_CHANGE:"CART_CHANGE",
};
